resource_types:
  - name: pull-request
    type: docker-image
    check_every: 24h
    source:
      repository: teliaoss/github-pr-resource

  - name: slack-notification
    type: docker-image
    check_every: 24h
    source:
      repository: cfcommunity/slack-notification-resource

resources:
  - type: git
    name: master
    icon: github
    webhook_token: 0gd4XZNL4Y94zYDLql3C
    check_every: 30m
    source:
      uri: https://github.com/buildo/retro.git
      branch: master
      git_crypt_key: ((git-crypt-key))

  - type: git
    name: tag
    icon: tag
    webhook_token: 0gd4XZNL4Y94zYDLql3C
    check_every: 30m
    source:
      uri: https://github.com/buildo/retro.git
      branch: master
      tag_filter: "*"

  - type: pull-request
    name: pr
    icon: source-pull
    webhook_token: 0gd4XZNL4Y94zYDLql3C
    check_every: 30m
    source:
      repository: buildo/retro
      access_token: ((github-token))

  - type: pull-request
    name: sbt-buildo-pr
    icon: source-pull
    webhook_token: 0gd4XZNL4Y94zYDLql3C
    check_every: 30m
    source:
      repository: buildo/retro
      access_token: ((github-token))
      paths:
        - build.sbt
        - project
        - sbt-buildo

  - type: pull-request
    name: enumero-pr
    icon: source-pull
    webhook_token: 0gd4XZNL4Y94zYDLql3C
    check_every: 30m
    source:
      repository: buildo/retro
      access_token: ((github-token))
      paths:
        - build.sbt
        - project
        - enumero

  - type: pull-request
    name: mailo-pr
    icon: source-pull
    webhook_token: 0gd4XZNL4Y94zYDLql3C
    check_every: 30m
    source:
      repository: buildo/retro
      access_token: ((github-token))
      git_crypt_key: ((git-crypt-key))
      paths:
        - build.sbt
        - project
        - mailo

  - type: pull-request
    name: toctoc-pr
    icon: source-pull
    webhook_token: 0gd4XZNL4Y94zYDLql3C
    check_every: 30m
    source:
      repository: buildo/retro
      access_token: ((github-token))
      paths:
        - build.sbt
        - project
        - toctoc

  - type: pull-request
    name: metarpheus-pr
    icon: source-pull
    webhook_token: 0gd4XZNL4Y94zYDLql3C
    check_every: 30m
    source:
      repository: buildo/retro
      access_token: ((github-token))
      paths:
        - build.sbt
        - project
        - metarpheus

  - type: pull-request
    name: tapiro-pr
    icon: source-pull
    webhook_token: 0gd4XZNL4Y94zYDLql3C
    check_every: 30m
    source:
      repository: buildo/retro
      access_token: ((github-token))
      paths:
        - build.sbt
        - project
        - tapiro

  - type: pull-request
    name: java-time-circe-codecs-pr
    icon: source-pull
    webhook_token: 0gd4XZNL4Y94zYDLql3C
    check_every: 30m
    source:
      repository: buildo/retro
      access_token: ((github-token))
      paths:
        - build.sbt
        - project
        - javaTimeCirceCodecs

  - type: pull-request
    name: wiro-pr
    icon: source-pull
    webhook_token: 0gd4XZNL4Y94zYDLql3C
    check_every: 30m
    source:
      repository: buildo/retro
      access_token: ((github-token))
      paths:
        - build.sbt
        - project
        - wiro

  - type: pull-request
    name: docs-pr
    icon: source-pull
    webhook_token: 0gd4XZNL4Y94zYDLql3C
    check_every: 30m
    source:
      repository: buildo/retro
      access_token: ((github-token))
      paths:
        - build.sbt
        - project
        - docs
        - ci/docs.yml

  - name: postgres
    type: registry-image
    icon: docker
    source:
      repository: postgres
      tag: "16.1-alpine"

  - name: mysql
    type: registry-image
    icon: docker
    source:
      repository: mysql
      tag: "8"

  - name: scala-sbt
    type: registry-image
    icon: docker
    source:
      repository: buildo/scala-sbt-alpine
      tag: 8_2.13.6_1.5.5

  - name: hseeberger-scala-sbt
    type: registry-image
    icon: docker
    source:
      repository: hseeberger/scala-sbt
      tag: 8u282_1.5.5_2.13.6

  - name: slack-buildo
    type: slack-notification
    icon: slack
    source:
      url: ((buildo-slack-hook))

__put_slack_failed_job: &slack_failure
  put: slack-buildo
  params:
    channel: "#backends"
    text: |
      The build of $BUILD_JOB_NAME failed :cry:
      See: $ATC_EXTERNAL_URL/builds/$BUILD_ID
  inputs: []

jobs:
  - name: sbt-buildo
    plan:
      - get: retro
        resource: master
        trigger: true
      - task: compile
        file: retro/sbt-buildo/ci/compile.yml
    on_failure:
      <<: *slack_failure

  - name: enumero
    plan:
      - get: retro
        resource: master
        trigger: true
      - task: test
        file: retro/enumero/ci/test.yml
    on_failure:
      <<: *slack_failure

  - name: mailo
    plan:
      - get: retro
        resource: master
        trigger: true
      - task: test
        file: retro/mailo/ci/test.yml
    on_failure:
      <<: *slack_failure

  - name: toctoc
    plan:
      - in_parallel:
          fail_fast: true
          steps:
            - get: retro
              resource: master
              trigger: true
            - get: postgres
              params: { format: oci }
            - get: mysql
              params: { format: oci }
            - get: scala-sbt
              params: { format: oci }
      - task: test
        file: retro/toctoc/ci/test.yml
        privileged: true
    on_failure:
      <<: *slack_failure

  - name: metarpheus
    plan:
      - get: retro
        resource: master
        trigger: true
      - task: test
        file: retro/metarpheus/ci/test.yml
    on_failure:
      <<: *slack_failure

  - name: tapiro
    plan:
      - get: retro
        resource: master
        trigger: true
      - task: test
        file: retro/tapiro/ci/test.yml
    on_failure:
      <<: *slack_failure

  - name: java-time-circe-codecs
    plan:
      - get: retro
        resource: master
        trigger: true
      - task: test
        file: retro/javaTimeCirceCodecs/ci/test.yml
    on_failure:
      <<: *slack_failure

  - name: wiro
    plan:
      - get: retro
        resource: master
        trigger: true
      - task: test
        file: retro/wiro/ci/test.yml
    on_failure:
      <<: *slack_failure

  - name: docs
    plan:
      - in_parallel:
          fail_fast: true
          steps:
            - get: retro
              resource: master
              trigger: true
            - get: hseeberger-scala-sbt
      - task: build-docs
        image: hseeberger-scala-sbt
        file: retro/ci/docs.yml
    on_failure:
      <<: *slack_failure

  - name: scalafmt
    plan:
      - get: retro
        resource: master
        trigger: true
      - task: scalafmt
        file: retro/ci/scalafmt.yml
    on_failure:
      <<: *slack_failure

  - name: sbt-buildo-pr
    plan:
      - get: retro
        resource: sbt-buildo-pr
        trigger: true
        version: every
      - put: sbt-buildo-pr
        params:
          path: retro
          status: pending
          context: sbt-buildo
      - task: compile
        file: retro/sbt-buildo/ci/compile.yml
    on_failure:
      put: sbt-buildo-pr
      params:
        path: retro
        status: failure
        context: sbt-buildo
    on_success:
      put: sbt-buildo-pr
      params:
        path: retro
        status: success
        context: sbt-buildo

  - name: enumero-pr
    plan:
      - get: retro
        resource: enumero-pr
        trigger: true
        version: every
      - put: enumero-pr
        params:
          path: retro
          status: pending
          context: enumero
      - task: test
        file: retro/enumero/ci/test.yml
    on_failure:
      put: enumero-pr
      params:
        path: retro
        status: failure
        context: enumero
    on_success:
      put: enumero-pr
      params:
        path: retro
        status: success
        context: enumero

  - name: mailo-pr
    plan:
      - get: retro
        resource: mailo-pr
        trigger: true
        version: every
      - put: mailo-pr
        params:
          path: retro
          status: pending
          context: mailo
      - task: test
        file: retro/mailo/ci/test.yml
    on_failure:
      put: mailo-pr
      params:
        path: retro
        status: failure
        context: mailo
    on_success:
      put: mailo-pr
      params:
        path: retro
        status: success
        context: mailo

  - name: toctoc-pr
    plan:
      - in_parallel:
          fail_fast: true
          steps:
            - get: retro
              resource: toctoc-pr
              trigger: true
              version: every
            - get: postgres
              params: { format: oci }
            - get: mysql
              params: { format: oci }
            - get: scala-sbt
              params: { format: oci }
      - put: toctoc-pr
        params:
          path: retro
          status: pending
          context: toctoc
      - task: test
        file: retro/toctoc/ci/test.yml
        privileged: true
    on_failure:
      put: toctoc-pr
      params:
        path: retro
        status: failure
        context: toctoc
    on_success:
      put: toctoc-pr
      params:
        path: retro
        status: success
        context: toctoc

  - name: metarpheus-pr
    plan:
      - get: retro
        resource: metarpheus-pr
        trigger: true
        version: every
      - put: metarpheus-pr
        params:
          path: retro
          status: pending
          context: metarpheus
      - task: test
        file: retro/metarpheus/ci/test.yml
    on_failure:
      put: metarpheus-pr
      params:
        path: retro
        status: failure
        context: metarpheus
    on_success:
      put: metarpheus-pr
      params:
        path: retro
        status: success
        context: metarpheus

  - name: tapiro-pr
    plan:
      - get: retro
        resource: tapiro-pr
        trigger: true
        version: every
      - put: tapiro-pr
        params:
          path: retro
          status: pending
          context: tapiro
      - task: test
        file: retro/tapiro/ci/test.yml
    on_failure:
      put: tapiro-pr
      params:
        path: retro
        status: failure
        context: tapiro
    on_success:
      put: tapiro-pr
      params:
        path: retro
        status: success
        context: tapiro

  - name: java-time-circe-codecs-pr
    plan:
      - get: retro
        resource: java-time-circe-codecs-pr
        trigger: true
        version: every
      - put: java-time-circe-codecs-pr
        params:
          path: retro
          status: pending
          context: javaTimeCirceCodecs
      - task: test
        file: retro/javaTimeCirceCodecs/ci/test.yml
    on_failure:
      put: java-time-circe-codecs-pr
      params:
        path: retro
        status: failure
        context: javaTimeCirceCodecs
    on_success:
      put: java-time-circe-codecs-pr
      params:
        path: retro
        status: success
        context: javaTimeCirceCodecs

  - name: wiro-pr
    plan:
      - get: retro
        resource: wiro-pr
        trigger: true
        version: every
      - put: wiro-pr
        params:
          path: retro
          status: pending
          context: wiro
      - task: test
        file: retro/wiro/ci/test.yml
    on_failure:
      put: wiro-pr
      params:
        path: retro
        status: failure
        context: wiro
    on_success:
      put: wiro-pr
      params:
        path: retro
        status: success
        context: wiro

  - name: docs-pr
    plan:
      - in_parallel:
          fail_fast: true
          steps:
            - get: retro
              resource: docs-pr
              trigger: true
              version: every
            - get: hseeberger-scala-sbt
      - put: docs-pr
        params:
          path: retro
          status: pending
          context: docs
      - task: build-docs
        image: hseeberger-scala-sbt
        file: retro/ci/docs.yml
    on_failure:
      put: docs-pr
      params:
        path: retro
        status: failure
        context: docs
    on_success:
      put: docs-pr
      params:
        path: retro
        status: success
        context: docs

  - name: scalafmt-pr
    plan:
      - get: retro
        resource: pr
        trigger: true
        version: every
      - put: pr
        params:
          path: retro
          status: pending
          context: scalafmt
      - task: scalafmt
        file: retro/ci/scalafmt.yml
    on_failure:
      put: pr
      params:
        path: retro
        status: failure
        context: scalafmt
    on_success:
      put: pr
      params:
        path: retro
        status: success
        context: scalafmt

  - name: release
    plan:
      - in_parallel:
          fail_fast: true
          steps:
            - get: retro
              resource: master
              trigger: true
              passed:
                - sbt-buildo
                - enumero
                - mailo
                - toctoc
                - metarpheus
                - tapiro
                - docs
                - wiro
                - scalafmt
                - java-time-circe-codecs
            - get: tag
              trigger: true
            - get: hseeberger-scala-sbt
      - task: release-on-sonatype
        image: hseeberger-scala-sbt
        file: retro/ci/release.yml
        params:
          GITHUB_DEPLOY_KEY: ((private-key))
          PGP_PASSPHRASE: ((sonatype_pgp_passphrase))
          PGP_SECRET: ((sonatype_pgp_secret_key))
          SONATYPE_USERNAME: ((sonatype_username))
          SONATYPE_PASSWORD: ((sonatype_password))
    on_success:
      put: slack-buildo
      params:
        channel: "#backends"
        text: |
          :tada: A new release has been successfully performed
      inputs: []
    on_failure:
      <<: *slack_failure
